### ISSUE TITLE
[U] 메인

### ISSUE THREAD

**Issue by soobinJung** [swgil007/DDaJa#12]
# 따자 메인 UI 개발 기록

- 자격증 종류 4가지 축소
    - 정보 처리 산업 기사
    - **정보 처리 기사**
    - 컴퓨터 활용 자격증 1급
    - 컴퓨터 활용 자격증 2급

- [x] 자격증별 이미지 그리기
- [x] LOGO 변경 예정
- [x]  합격자 현황
- [x]  실시간 현황
- [x]  응시 D DAY
- [x]  커뮤니티

**Comment by swgil007** [comment]
메인 어디까지 됐어욤

**Comment by soobinJung** [comment]
진행 중 입니다 재촉하지 마세요 ┗( T﹏T )┛

**Comment by soobinJung** [comment]
![computer-utilize-one](https://user-images.githubusercontent.com/66097044/116553957-a1eda900-a935-11eb-907d-fe7862af0e3f.jpg)
![computer-utilize-one-hover](https://user-images.githubusercontent.com/66097044/116553962-a31ed600-a935-11eb-8a3b-fb251b05d724.jpg)
![computer-utilize-two](https://user-images.githubusercontent.com/66097044/116553966-a3b76c80-a935-11eb-9b25-fc01502a774d.jpg)
![computer-utilize-two-hover](https://user-images.githubusercontent.com/66097044/116553969-a3b76c80-a935-11eb-8d82-81cd1131e885.jpg)
![jeongbo-cheoli-gisa](https://user-images.githubusercontent.com/66097044/116553970-a4500300-a935-11eb-8a0f-d915ff0504d4.jpg)
![jeongbo-cheoli-gisa-hover](https://user-images.githubusercontent.com/66097044/116553972-a4500300-a935-11eb-9cd0-4e312ad7bc1c.jpg)
![jeongbo-cheoli-sanup-gisa](https://user-images.githubusercontent.com/66097044/116553973-a4e89980-a935-11eb-95b8-1ba609cf80a2.jpg)
![jeongbo-cheoli-sanup-gisa-hover](https://user-images.githubusercontent.com/66097044/116553975-a4e89980-a935-11eb-85f7-249b1248f9a8.jpg)

**Comment by soobinJung** [comment]
**오늘 자격증 카테고리 연결고리 기요미들은 업데이트 했습니다!**
